spring.application.name=SERVICE-REGISTRY
server.port=8761
#disable on client
#By using these prooperteis eureka work as a server not cluent
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
