spring.application.name=QUESTION-SERVICE

#server.port=8082
#STEP 2 HAMNE CONFIGURATION ADD KI EUREKW KI POM.XML FILE sabse pehal hame serviceregistry ko start krna ha phir questionservice phir quizservice
# 2.1 fir hamne question service band ki aur use terminal pr run kiya
#2.2 uska step ha ki sabse pehla right side meh jo maven ha -> QuestionService -> LifeCycle ->package -copy jar file name -> open in exxplorer -open in termianl

#2.2 termianl phir uss jar file ko aesa likha java -jar .\QuestionService-0.0.1-SNAPSHOT.jar fir wahpr run ho jaayegi
#2.3  phir yahpar serverport ko change kare 9092 or any number
#2.4 abhi ham load-balancing kar rahe ha eureka server pr 2
#2.5 isliya ise bhi run karnegeh fir postman api pr http://localhost:8081/quiz/1  ise run karnegh toh data call hoga sab
#2.6 lekin suppose agar service down ho 8082 waali jo humne termnial se start ki toh fir
#2.7 agar ek service down hogi toh request dusir server/instance pe kesa shift hogi abhi ham dekhngeh ise
#2.8 spring load-balancer ki depency file ham add karnegeh pehaa  quiz-service ki pom .xml file meh

#server.port=8082
server.port=9092


spring.datasource.url=jdbc:mysql://localhost:3306/micro_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



eureka.client.service-url.defaultZone=http://localhost:8761/eureka/