spring.application.name=API-GATEWAY
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoint.gateway.access=read-only
management.endpoints.web.exposure.include=gateway,health

#routes configuration
#4 aab ek central api gateway hoga yahpar ham saari instance/service route karnegeh jesa ki yahpr likha quiz-service
spring.cloud.gateway.server.webmvc.routes[0].id=QUIZ-SERVICE

#4.1 yahpr lb metlab ha loab-balancing ,iskamatlab ha ki suppose yeh instance alag alag port pr chalu hogi toh toh property use balance kar legi
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://QUIZ-SERVICE

#4.2 yahpar ham path set kr ra ha ki /quiz ke baad jo jo service mhe usa ham call kr saktah ha
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/quiz/**,/quiz-test/**


spring.cloud.gateway.server.webmvc.routes[1].id=QUESTION-SERVICE

spring.cloud.gateway.server.webmvc.routes[1].uri=lb://QUESTION-SERVICE

spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/question/**